#!/bin/bash

generate_secret() {
    secret=""
    while [ ${#secret} -lt 4 ]; do
        digit=$((RANDOM % 10))
        if [[ ! $secret =~ $digit ]]; then
            secret+=$digit
        fi
    done
    echo "$secret"
}

calculate_bulls_and_cows() {
    local guess=$1
    local secret=$2
    bulls=0
    cows=0

    for ((i=0; i<${#guess}; i++)); do
        if [ "${guess:i:1}" == "${secret:i:1}" ]; then
            bulls=$((bulls + 1))
        elif [[ $secret == *"${guess:i:1}"* ]]; then
            cows=$((cows + 1))
        fi
    done

    echo "$bulls $cows"
}

secret=$(generate_secret)
attempts=0

echo "Быки и коровы"
echo "Попытайся угадать 4 значное число, все цифры уникальные"

while true; do
    read -p "Угадай число: " guess

    # Validate input
    if ! [[ $guess =~ ^[0-9]{4}$ ]] || [[ $guess =~ (.)\1 ]]; then
        echo "Введи 4 цифры"
        continue
    fi

    attempts=$((attempts + 1))
    result=$(calculate_bulls_and_cows "$guess" "$secret")
    bulls=$(echo $result | cut -d' ' -f1)
    cows=$(echo $result | cut -d' ' -f2)

    echo "$bulls Быков, $cows Коровы"

    if [ "$bulls" -eq 4 ]; then
        echo "Поздравляю ты угадал $secret за $attempts попытки."
        break
    fi
done
